name: "\U0001F41E Bug Report"
description: Report a bug in Virtual Media Folders - Folder Exporter
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below so we can investigate and fix it as quickly as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise summary of what the bug is.
      placeholder: Describe the bug…
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      value: |
        1. Go to …
        2. Click on …
        3. Scroll down to …
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected…
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened…
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: If applicable, add screenshots or screen recordings to help explain the problem. You can drag and drop images here.
      placeholder: Drag and drop images or paste links here…
    validations:
      required: false

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of Folder Exporter are you running?
      placeholder: "1.1.0"
    validations:
      required: true

  - type: input
    id: wp-version
    attributes:
      label: WordPress Version
      description: Which version of WordPress are you running?
      placeholder: "6.8"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: Which version of PHP is your server running?
      placeholder: "8.3"
    validations:
      required: true

  - type: dropdown
    id: export-type
    attributes:
      label: Export Type
      description: How are you triggering the export? (if applicable)
      options:
        - Admin UI (React panel)
        - WP-CLI command
        - REST API
        - Not applicable
    validations:
      required: false

  - type: checkboxes
    id: export-options
    attributes:
      label: Export Options Used
      description: Which options were enabled during the export?
      options:
        - label: Include subtrees
        - label: CSV manifest
        - label: Background processing

  - type: input
    id: folder-size
    attributes:
      label: Folder Size
      description: Approximately how many files are in the exported folder? (helps reproduce performance issues)
      placeholder: "e.g. 50, 500, 5000"
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using? (if relevant)
      placeholder: "e.g. Chrome 120, Safari 17, Firefox 121"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem — e.g. other active plugins, theme, multisite, error log output, server disk space.
      placeholder: Any other details that might help…
    validations:
      required: false
